## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **16 pts**

\begin{equation}
\begin{array}{ccc}
2x+3y−z+4w+5v&=&15\\
x - 2y + 4z - 3w + v &=& 6\\
3x+2y−3z+5w−2v&=&11 \\
4x+y−2z+3w+2v&=&8 \\
x+y+z+w+v&=&7
\end{array}
\end{equation}


#### Solucion

Se extraen todos los coeficientes del sistema de ecuaciones  para dejar la siguiente matriz

\begin{pmatrix}
2 & 3 & -1 &4 & 5 &|& 15 \\
1 & -2&4&-3&1 &|& 6\\
3&2&−3&5&−2&|&11 \\
4&1&−2&3&2&|&8 \\
1&1&1&1&1&|&7
\end{pmatrix}

In [1]:
# Se importa el paquete NumPy
import numpy as np

In [2]:
# se contruye la matriz en Python
matriz_a = np.array([
    [2,3,-1,4,5],
    [1,-2,4,-3,1],
    [3,2,-3,5,-2],
    [4,1,-2,3,2],
    [1,1,1,1,1]
])
# y tambien el vector respuesta
matriz_b = np.array([15,6,11,8,7])

# se muestran ambos array para validar.
print(matriz_a )
print(matriz_a )

[[ 2  3 -1  4  5]
 [ 1 -2  4 -3  1]
 [ 3  2 -3  5 -2]
 [ 4  1 -2  3  2]
 [ 1  1  1  1  1]]
[[ 2  3 -1  4  5]
 [ 1 -2  4 -3  1]
 [ 3  2 -3  5 -2]
 [ 4  1 -2  3  2]
 [ 1  1  1  1  1]]


In [3]:
def resolverSistemaEcuaciones(A:np.array,b:np.array):
  """
  Función que recibe la matriz cuadrada A y el vector de resultado b y retorna la solución al sistema de ecuacines

  A: Es la matriz cuadradrada n x n
  b: es el vector de resultados 1xn

  ambis argumentos deben ser de tipo Array del paquete numpy (numpy.array)
  Ex:
    In[0]: A:[[2, 3,-1],
              [4,-2, 3],
              [1, 1, 2]]
           b: [8,-1,10]
    Out[0]: Las soluciones al sistema de ecuaciones es (2, 2,3)
  """
  # primero se convierte las entrdas en tipo flotatne para su operación,
  # ya que si se dejan en su tipo orignal pueden haber errores de calculo por ser entero
  A = A.astype(float)
  b = b.astype(float)
  #se comprueba que los array ingresados cumplan con la única condicion descrita anteriormente para su ejecución
  if(A.shape[0]==b.shape[0] and  A.shape[0]== A.shape[1]):
    # Se una la matriz completa.
    matriz_completa = np.column_stack((A, b))
    matriz_completa.astype(float)
    ##print(matriz_completa)
    ##print("========================\n========================")
    # se tiene la cantidad de filas/variables para resolver
    dim_matriz = len(matriz_completa)


    # se hace un ciclo por cada fila para volverla una matriz identidad
    for i in range(dim_matriz):
      # se escoge el numero pivot actual de la fila i
      pivot_i = matriz_completa[i,i]

      #se transforma fila i para que el pivot quede 1.
      matriz_completa[i] = matriz_completa[i] * (1/pivot_i)

      #print(matriz_completa[i] * (1/pivot_i))
      #Se crea un bucle interno para convertir toda la matriz triangualar inferior en 0
      for j in range(i+1,dim_matriz):

        #se toma el valor i,j de la matriz_completa que se llamará factor
        factor_fila_j = matriz_completa[j,i]

        matriz_completa[j] -=  matriz_completa[i] * factor_fila_j
        #se multiplica toda la fila i matriz por este facor y se resta a si misma
        #print(matriz_completa)

      #print("=======================")
      # y se hace el último ciclo para convertir toda la matriz triangular superior en 0
      for k in range(i):
        factor_fila_k = matriz_completa[k,i]

        matriz_completa[k] -= matriz_completa[i] * factor_fila_k
        #print(matriz_completa)

    #se obtiene el siguiente resultado
    resultado = matriz_completa[:,-1]
    # se pone en las columnas -1 para solo exportar la última columna de la matriz que contiene los resultados del sistema de ecaciones
    #print(matriz_completa)

    print("La solución al sistema de ecuaciones es:")
    print(resultado)
    return resultado
  else:
    print("La matrices ingresadas no cuentan con la condinción para su resolución\n la matriz A debe ser nxn y el vector b debe ser 1xn")
    return None



In [4]:
resolverSistemaEcuaciones(matriz_a,matriz_b)
-52/31

La solución al sistema de ecuaciones es:
[-1.67741935 -7.87096774  5.12903226 10.          1.41935484]


-1.6774193548387097

**2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:**

$$e = \sum_i ^{\infty} \frac{1}{n!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **18 pts**

#### Solucion 

In [5]:
import numpy as np

euler_solicitado = 2.71828 # Valor número euler solicitado

# La siguiente función tiene como objeto hacer el caculo del factorial (!) de un número, mediante numpy.
# se logra calculando el producto de todos los valores de un vector iniciado en 1 hasta el valor que se desea calcular.

def factorial(z): #calculo factorial
    return np.prod(np.arange(1, z + 1))

# La siguiente función tiene como objeto calcular el valor de la sumatoria de (1/n), se deja dentro de un vector usando cumsum en lugar de sum, con el fin de poder usar
# argmax para poder calcular el valor minimo de "n" en lugar de un condicional.
def prueba(m):
   vector = np.arange(m +1) # creación del vector de valores que tomará "n" en la sumatoría (inicia en cero hasta el valor a calcular)
   vector_factorial = np.vectorize(factorial)(vector) # vector de valores de "n!"
   vector_factorial_inverso = (1 / vector_factorial) # vector de valores dde "1/n!"
   return np.cumsum(vector_factorial_inverso) # vector de valoers de "sumatirias de "1/n!""

k = np.argmax(prueba(20) > euler_solicitado) # Dado que es una sumatoria, una vez superado el valor de Euler solicitado se cumple con la condición dada por el ejercicio,
#así pues el valor máximo del vector que cumple la condición es el valor solicitado. Por otro lado se asume que “20” es un valor “infinito”

p = prueba(k)[-1] # valor de euler calculado, se entiende que es último número del vector k


print ("el valor de euler calculado es:", p) # se imprime el resultado del valor de euler calculado
print ("el numero de terminos que se necesita para dar cuenta de los primeros 5 números de la coma desimal es:", k) # se imprime el resultado del numero mínimo de terminos


el valor de euler calculado es: 2.7182815255731922
el numero de terminos que se necesita para dar cuenta de los primeros 5 números de la coma desimal es: 9



**3. Encuentre los auto valores de la matriz.**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$


#### Solucion

Tenga en cuenta que para hallar los autovalores para la matriz (que llamaremos $A$), se debe cumplir que:
- $A$ debe ser una matriz cuadra de $n \times n$



In [ ]:
# transcribimos la matriz A en python
A = np.array(
    [
        [2,1,1],
        [4,3,2],
        [1,1,2]
    ]
)
print(A)

[[2 1 1]
 [4 3 2]
 [1 1 2]]


In [ ]:
import numpy as np

def metodo_potencia(A, num_iteraciones=1000, minimo_e=1e-6):
  """
    Función que recibe la matriz cuadrada A y como resultado se obtiene los autovalores de la matriz A

    A: Es la matriz cuadradrada n x n
    num_iteraciones: Cantidad de iteraciones para ejecutar el método
    minimo_e: error nínimo admitido

    Ex:
      In[0]: A = np.array([[0.5, 0.5], [0.2, 0.8]]),
           n = 10
      Out[0]: los autovalores son: array([0.70710403, 0.70710954])
  """

  # Elegir un vector inicial aleatorio
  vector_aleatorio = np.random.rand(A.shape[0])

    # Iterar hasta converger o alcanzar el número máximo de iteraciones
  for iteracion_actual in range(num_iteraciones):

        # Multiplicar la matriz por el vector aleatorio
        Ax = A.dot(vector_aleatorio)

        # Normalizar el vector resultante
        vector_nuevo = Ax / np.linalg.norm(Ax)

        # Calcular el autovalor aproximado
        autovalor = vector_nuevo.dot(Ax)

        # Comprobar la convergencia
        if np.linalg.norm(vector_nuevo - vector_aleatorio) < minimo_e:
            break

        vector_aleatorio = vector_nuevo

  print("Autovalor dominante:", autovalor)
  print("Autovector asociado:", autovector)
  return autovalor, vector_aleatorio

# Calcular el autovalor dominante y su autovector aproximado
autovalor, autovector = metodo_potencia(A)

Autovalor dominante: 5.4494879924790895
Autovector asociado: [0.35355347 0.86602515 0.35355392]
